### ISSUE TITLE
Error when parsing JSON with floats

### ISSUE THREAD

**Issue by majsan** [spraakbanken/json-streams-py#7]
In version 0.12.3, parsing a JSON file adds `Decimal` to the result. This does not happen for JSONL.

```
>>> list(json_streams.load_from_file("test.json"))
[{'value': Decimal('1.2')}]
>>> list(json_streams.load_from_file("test.jsonl"))
[{'value': 1.2}]
```

Contents of `test.json`:
```
[{"value": 1.2}]
```

Contents of `test.jsonl`:
```
{"value": 1.2}
```

**Comment by kod-kristoff** [comment]
Oh, they should of course return the same, I prefer `float` as default, and `Decimal` optional, what do you think?

**Comment by majsan** [comment]
Never seen the `Decimal` thing before, so no opinion!
